apiVersion: v1
kind: ServiceAccount
metadata:
  name: razeedeploy-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: razeedeploy-admin-cr
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: razeedeploy-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: razeedeploy-admin-cr
subjects:
- kind: ServiceAccount
  name: razeedeploy-sa
  namespace: default
- kind: User
  name: minikube-user
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-webhook
  template:
    metadata:
      labels:
        app: test-webhook
      name: test-webhook
    spec:
      serviceAccountName: razeedeploy-sa
      containers:
      - image: test-webhook:latest
        name: test-webhook
        imagePullPolicy: Never
        ports:
        - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: test-webhook
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: test-webhook