apiVersion: v1
kind: List
metadata:
  name: impersonation-webhook-list
  annotations:
    razee.io/git-repo: "{{{GIT_REMOTE}}}"
    razee.io/commit-sha: "{{{TRAVIS_COMMIT}}}"
    version: "{{{TRAVIS_COMMIT}}}"
type: array
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: impersonation-webhook
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: impersonation-webhook
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: impersonation-webhook
          name: impersonation-webhook
        spec:
          serviceAccountName: razeedeploy-sa
          securityContext:
            runAsUser: {{{NODE_USER_ID}}}
            runAsGroup: {{{NODE_GROUP_ID}}}
            fsGroup: {{{NODE_GROUP_ID}}}
          containers:
          - image: "quay.io/razee/impersonation-webhook:{{{TRAVIS_TAG}}}"
            resources:
              limits:
                memory: 200Mi
                cpu: 100m
              requests:
                memory: 75Mi
                cpu: 40m
            env:
              - name: USER_AGENT_NAME
                value: razee-io/impersonation-webhook
              - name: USER_AGENT_VERSION
                value: "{{{TRAVIS_TAG}}}"
              - name: TLS_CA
                valueFrom:
                  secretKeyRef:
                    name: impersonation
                    key: ca.crt
              - name: TLS_CERT
                valueFrom:
                  secretKeyRef:
                    name: impersonation
                    key: tls.crt
              - name: TLS_KEY
                valueFrom:
                  secretKeyRef:
                    name: impersonation
                    key: tls.key
            name: impersonation-webhook
            imagePullPolicy: Never
            ports:
            - containerPort: 8443
            readinessProbe:
              httpGet:
                scheme: HTTPS
                path: /readyz
                port: 8443
            livenessProbe:
              httpGet:
                scheme: HTTPS
                path: /livez
                port: 8443
  - apiVersion: v1
    kind: Service
    metadata:
      name: impersonation-webhook
    spec:
      ports:
      - port: 443
        protocol: TCP
        targetPort: 8443
      selector:
        app: impersonation-webhook
